apiVersion: v1
kind: Pod
metadata: 
  name: livenessprobe-pod
spec:
  containers:
  - name: livenessprobe-test
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
     # http get方法
     #  httpGet: 
     #    path: /_status/healthz  # 文件已存在
     #    port: 80
     
      # TCPSocket
      tcpSocket:
        port: 80

      initialDelaySeconds: 10   # 启动容器后进行首次健康检查的等待时间，单位s
      timeoutSeconds: 1         # 健康检查发送请求后等待响应的超时时间，单位s。超时后重启容器
