---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1

---
apiVersion: v1
kind: Service
metadata:
  name: lb-myapp
  labels:
    app: lb-myapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp



