---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    pv_name: pv-1
spec:
  accessModes: 
  - ReadWriteMany
  nfs:
    path: /data/volumes/v1
    server: 192.168.226.100
  capacity:
    storage: 5Gi
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
  labels:
    pv_name: pv-2
spec:
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/volumes/v2
    server: 192.168.226.100
  capacity:
    storage: 3Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv3
  labels:
    pv_name: pv-3
spec:
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/volumes/v3
    server: 192.168.226.100
  capacity:
    storage: 2Gi
